apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy1-httpd
spec:
 replicas: 1
 selector:
   matchLabels:
     app: httpd
 template:
   metadata:
     labels:
       app: httpd
   spec:
     containers:
     - name: pod-httpd
       image: nescafe1220/aa:httpd2.4
---
apiVersion: v1
kind: Service
metadata:
 name: svc1-httpd
spec:
 ports:
   - name: httpd-port
     port: 80
     targetPort: 80
 selector:
   app: httpd
 type: NodePort
