apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy1-tomcat
spec:
 replicas: 1
 selector:
   matchLabels:
     app: tomcat
 template:
   metadata:
     labels:
       app: tomcat
   spec:
     containers:
     - name: pod-tomcat
       image: nescafe1220/aa:tomcat9
---
apiVersion: v1
kind: Service
metadata:
 name: svc1-tomcat
spec:
 ports:
   - name: tomcat-port
     port: 8009
     targetPort: 8009
 selector:
   app: tomcat
 type: NodePort
